### ISSUE TITLE
whisper开始转写报错，阿里ASR和必剪ASR都可以用，什么原因阿

### ISSUE THREAD

**Issue by daxige9527** [v3ucn/ASR_TOOLS_WebUI#1]
Error: Traceback (most recent call last):
  File "F:\Bert-Vits2_Audio_Tool\short_audio_transcribe_whisper.py", line 162, in <module>
    text = transcribe_one(f"{input_file}"+wav_file,mytype)
  File "F:\Bert-Vits2_Audio_Tool\short_audio_transcribe_whisper.py", line 51, in transcribe_one
    audio = whisper.load_audio(audio_path)
  File "F:\Bert-Vits2_Audio_Tool\venv\lib\site-packages\whisper\audio.py", line 58, in load_audio
    out = run(cmd, capture_output=True, check=True).stdout
  File "F:\Bert-Vits2_Audio_Tool\venv\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "F:\Bert-Vits2_Audio_Tool\venv\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "F:\Bert-Vits2_Audio_Tool\venv\lib\subprocess.py", line 1436, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by daxige9527** [comment]
Active code page: 65001
.\venv\python.exe
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
01-21 17:31:53 |  INFO  | subprocess_utils.py:14 | Running: short_audio_transcribe_whisper.py --model_name em --language zh --mytype medium --input_file  --file_pos
['.\\venv\\python.exe', 'short_audio_transcribe_whisper.py', '--model_name', 'em', '--language', 'zh', '--mytype', 'medium', '--input_file', '', '--file_pos', '']
  0%|                                                                                            | 0/9 [00:00<?, ?it/s]
01-21 17:32:00 | ERROR  | subprocess_utils.py:25 | Error: short_audio_transcribe_whisper.py --model_name em --language zh --mytype medium --input_file  --file_pos
Traceback (most recent call last):
  File "F:\Bert-Vits2_Audio_Tool\short_audio_transcribe_whisper.py", line 162, in <module>
    text = transcribe_one(f"{input_file}"+wav_file,mytype)
  File "F:\Bert-Vits2_Audio_Tool\short_audio_transcribe_whisper.py", line 51, in transcribe_one
    audio = whisper.load_audio(audio_path)
  File "F:\Bert-Vits2_Audio_Tool\venv\lib\site-packages\whisper\audio.py", line 58, in load_audio
    out = run(cmd, capture_output=True, check=True).stdout
  File "F:\Bert-Vits2_Audio_Tool\venv\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "F:\Bert-Vits2_Audio_Tool\venv\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "F:\Bert-Vits2_Audio_Tool\venv\lib\subprocess.py", line 1436, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

01-21 17:32:59 |  INFO  | subprocess_utils.py:14 | Running: short_audio_transcribe_whisper.py --model_name em --language zh --mytype medium --input_file F:\Bert-Vits2_Audio_Tool\wavs\ --file_pos F:\Bert-Vits2_Audio_Tool\wavs\
['.\\venv\\python.exe', 'short_audio_transcribe_whisper.py', '--model_name', 'em', '--language', 'zh', '--mytype', 'medium', '--input_file', 'F:\\Bert-Vits2_Audio_Tool\\wavs\\', '--file_pos', 'F:\\Bert-Vits2_Audio_Tool\\wavs\\']
  0%|                                                                                            | 0/9 [00:00<?, ?it/s]
01-21 17:33:05 | ERROR  | subprocess_utils.py:25 | Error: short_audio_transcribe_whisper.py --model_name em --language zh --mytype medium --input_file F:\Bert-Vits2_Audio_Tool\wavs\ --file_pos F:\Bert-Vits2_Audio_Tool\wavs\
Traceback (most recent call last):
  File "F:\Bert-Vits2_Audio_Tool\short_audio_transcribe_whisper.py", line 162, in <module>
    text = transcribe_one(f"{input_file}"+wav_file,mytype)
  File "F:\Bert-Vits2_Audio_Tool\short_audio_transcribe_whisper.py", line 51, in transcribe_one
    audio = whisper.load_audio(audio_path)
  File "F:\Bert-Vits2_Audio_Tool\venv\lib\site-packages\whisper\audio.py", line 58, in load_audio
    out = run(cmd, capture_output=True, check=True).stdout
  File "F:\Bert-Vits2_Audio_Tool\venv\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "F:\Bert-Vits2_Audio_Tool\venv\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "F:\Bert-Vits2_Audio_Tool\venv\lib\subprocess.py", line 1436, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

求大神帮忙~~！！

**Comment by v3ucn** [comment]
您好，没有安装ffmpeg，或者没有配置ffmpeg的环境变量

请使用winget install ffmpeg 进行安装

**Comment by daxige9527** [comment]
谢谢大神 我试一下~！！

**Comment by daxige9527** [comment]
> 您好，没有安装ffmpeg，或者没有配置ffmpeg的环境变量
> 
> 请使用winget install ffmpeg 进行安装
谢大神  好啦 就是这个问题~！！！！！！
